openapi: 3.0.0
info:
  title: Naval Battle Game API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

paths:
  /battleships:
    get:
      summary: Service Information or Health Check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                    example: "Naval Battle Game API is running. For game operations, use /battleships/game/* endpoints."

  /battleships/game/start:
    post:
      summary: Start a New Game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  gameId:
                    type: string
                  message:
                    type: string
        '400':
          description: BAD REQUEST - Invalid parameters

  /battleships/game/fire:
    post:
      summary: Fire at Opponent
      parameters:
        - name: gameId
          in: query
          required: true
          schema:
            type: string
        - name: cell
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  consequence:
                    type: string
                    enum:
                      - miss
                      - hit
                      - sunk
                  shipLeft:
                    type: boolean
        '400':
          description: BAD REQUEST - Invalid parameters

  /battleships/game/stop:
    post:
      summary: Stop the Game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                gameId:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: BAD REQUEST - Invalid parameters
